name: Docker CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: docker build -f build.Dockerfile .
