name: Docker CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: adopt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - run: docker build .
