# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test
        run: |
          ./gradlew check
          ./gradlew jacocoTestReport
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build
        run: ./gradlew --no-daemon build
